#!/bin/zsh
# Install (or refresh) the scheduled Podium sync on this Mac.
#
# WHY A COPY OUTSIDE THE REPO
# The repo lives under ~/Documents, which macOS protects with TCC. A launchd agent
# gets no access there: pointed straight at scripts/, it dies with
#   /bin/zsh: can't open input file: .../scripts/podium-sync-run.sh   (exit 127)
# before running a line. The alternative is granting Full Disk Access to /bin/zsh or
# node, which is a large permission to hand a scheduled job. So the agent runs from
# ~/.rinkhockey/podium-sync, which TCC does not cover, and this script is what puts
# a current copy there.
#
# CONSEQUENCE: the installed copy is a SNAPSHOT. Change scripts/podium-sync.mjs and
# the agent keeps running the old one until you re-run this. It is idempotent —
# re-running is the refresh.
#
#   ./scripts/install-podium-agent.sh
set -euo pipefail

REPO="${0:A:h:h}"
DEST="$HOME/.rinkhockey/podium-sync"
LABEL="com.rinkhockeyil.podium-sync"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
NODE="$(command -v node || echo /opt/homebrew/bin/node)"

[[ -f "$REPO/.env.podium" ]] || { echo "✗ $REPO/.env.podium is missing — create it first."; exit 1; }

mkdir -p "$DEST"
cp "$REPO/scripts/podium-sync.mjs" "$DEST/podium-sync.mjs"
# Credentials travel with it; keep them readable only by this user.
cp "$REPO/.env.podium" "$DEST/.env.podium"
chmod 600 "$DEST/.env.podium"

# The script imports @supabase/supabase-js, and node resolves modules from the
# script's own directory upward — outside the repo there is no node_modules to find,
# so the copy gets its own.
cat > "$DEST/package.json" <<'JSON'
{ "name": "podium-sync-agent", "private": true, "type": "module",
  "dependencies": { "@supabase/supabase-js": "^2" } }
JSON
(cd "$DEST" && npm install --silent --no-audit --no-fund >/dev/null)

cat > "$DEST/run.sh" <<RUNNER
#!/bin/zsh
# Generated by install-podium-agent.sh — edit the repo copy, not this.
set -u
LOG="\$HOME/Library/Logs/podium-sync.log"
mkdir -p "\$(dirname "\$LOG")"
# Keep a few hundred KB of history; this runs four times a day forever.
if [[ -f "\$LOG" && \$(stat -f%z "\$LOG") -gt 1048576 ]]; then
  tail -c 262144 "\$LOG" > "\$LOG.tmp" && mv "\$LOG.tmp" "\$LOG"
fi
{
  echo "──────── \$(date '+%Y-%m-%d %H:%M:%S %Z') ────────"
  cd "$DEST" || exit 1
  "$NODE" podium-sync.mjs
  echo "exit=\$?"
} >> "\$LOG" 2>&1
RUNNER
chmod +x "$DEST/run.sh"

mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/install-podium-agent.sh. Runs the copy in ~/.rinkhockey,
     not the repo: see that script for why (macOS TCC on ~/Documents). -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>/bin/zsh</string><string>$DEST/run.sh</string></array>
  <key>StartCalendarInterval</key>
  <array>
    <dict><key>Hour</key><integer>7</integer><key>Minute</key><integer>30</integer></dict>
    <dict><key>Hour</key><integer>12</integer><key>Minute</key><integer>30</integer></dict>
    <dict><key>Hour</key><integer>17</integer><key>Minute</key><integer>30</integer></dict>
    <dict><key>Hour</key><integer>22</integer><key>Minute</key><integer>30</integer></dict>
  </array>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/podium-sync.launchd.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/podium-sync.launchd.log</string>
</dict>
</plist>
PLISTEOF

plutil -lint "$PLIST" >/dev/null
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo "✓ installed to $DEST"
echo "  runs 07:30 / 12:30 / 17:30 / 22:30"
echo "  log:  ~/Library/Logs/podium-sync.log"
echo "  now:  launchctl kickstart -p gui/\$(id -u)/$LABEL"
echo "  off:  launchctl bootout gui/\$(id -u)/$LABEL"
