#!/bin/zsh
# Install (or refresh) the weekly Supabase backup on this Mac.
#
# Runs scripts/backup-supabase.mjs every Sunday 09:00 into ~/Backups/rinkhockeyil
# (outside ~/Documents on purpose: that folder is iCloud-synced and the backup holds
# PII). launchd runs a missed date on the next wake, so a sleeping Mac only delays it.
#
# Same layout as install-podium-agent.sh, for the same reason: launchd jobs can't
# read ~/Documents (macOS TCC), so the agent runs a copy in ~/.rinkhockey. The copy
# is a SNAPSHOT — re-run this after changing scripts/backup-supabase.mjs, or after
# rotating the Supabase token / service key.
#
#   ./scripts/install-backup-agent.sh
set -euo pipefail

REPO="${0:A:h:h}"
DEST="$HOME/.rinkhockey/backup"
LABEL="com.rinkhockeyil.backup"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
NODE="$(command -v node || echo /opt/homebrew/bin/node)"

val() { grep -h "^$1=" "$REPO/.env" "$REPO/.env.podium" 2>/dev/null | head -1 | cut -d= -f2-; }
TOKEN="$(val SUPABASE_ACCESS_TOKEN)"; REF="$(val SUPABASE_PROJECT_REF)"; SERVICE="$(val SUPABASE_SERVICE_ROLE_KEY)"
[[ -n "$TOKEN" && -n "$REF" && -n "$SERVICE" ]] || { echo "✗ need SUPABASE_ACCESS_TOKEN, SUPABASE_PROJECT_REF (.env) and SUPABASE_SERVICE_ROLE_KEY (.env.podium)"; exit 1; }

mkdir -p "$DEST"
cp "$REPO/scripts/backup-supabase.mjs" "$DEST/backup-supabase.mjs"
cat > "$DEST/.env.backup" <<ENV
SUPABASE_ACCESS_TOKEN=$TOKEN
SUPABASE_PROJECT_REF=$REF
SUPABASE_SERVICE_ROLE_KEY=$SERVICE
ENV
chmod 600 "$DEST/.env.backup"

cat > "$DEST/run.sh" <<RUNNER
#!/bin/zsh
# Generated by install-backup-agent.sh — edit the repo copy, not this.
set -u
LOG="\$HOME/Library/Logs/rinkhockey-backup.log"
mkdir -p "\$(dirname "\$LOG")"
{
  echo "──────── \$(date '+%Y-%m-%d %H:%M:%S %Z') ────────"
  cd "$DEST" || exit 1
  set -a; source ./.env.backup; set +a
  "$NODE" backup-supabase.mjs
  rc=\$?
  echo "exit=\$rc"
  [[ \$rc -eq 0 ]] || osascript -e 'display notification "Weekly league backup FAILED — see ~/Library/Logs/rinkhockey-backup.log" with title "rinkhockeyIL"'
} >> "\$LOG" 2>&1
RUNNER
chmod +x "$DEST/run.sh"

mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/install-backup-agent.sh. Runs the copy in ~/.rinkhockey,
     not the repo: see that script for why (macOS TCC on ~/Documents). -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>/bin/zsh</string><string>$DEST/run.sh</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Weekday</key><integer>0</integer><key>Hour</key><integer>9</integer><key>Minute</key><integer>0</integer></dict>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/rinkhockey-backup.launchd.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/rinkhockey-backup.launchd.log</string>
</dict>
</plist>
PLISTEOF

plutil -lint "$PLIST" >/dev/null
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo "✓ installed to $DEST"
echo "  runs Sundays 09:00 → ~/Backups/rinkhockeyil"
echo "  log:  ~/Library/Logs/rinkhockey-backup.log"
echo "  now:  launchctl kickstart -p gui/\$(id -u)/$LABEL"
echo "  off:  launchctl bootout gui/\$(id -u)/$LABEL"
