#!/bin/zsh
# Install (or refresh) the monthly Apple-secret renewal on this Mac.
#
# Apple caps the web sign-in client secret at 6 months, so this re-signs it on the
# 1st of every month and PATCHes it into Supabase — it never gets near expiry.
# launchd runs a missed date on the next wake, so a sleeping Mac only delays it.
#
# Same layout as install-podium-agent.sh, for the same reason: launchd jobs can't
# read ~/Documents (macOS TCC), so the agent runs a copy in ~/.rinkhockey. The copy
# is a SNAPSHOT — re-run this after changing scripts/apple-secret-renew.mjs, or after
# rotating the Supabase token in .env.
#
#   ./scripts/install-apple-secret-agent.sh
set -euo pipefail

REPO="${0:A:h:h}"
DEST="$HOME/.rinkhockey/apple-secret"
LABEL="com.rinkhockeyil.apple-secret"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
NODE="$(command -v node || echo /opt/homebrew/bin/node)"
KEY_ID=J984K4BSP7
P8="$REPO/../rinkhockeyIL-signing/AuthKey_$KEY_ID.p8"

[[ -f "$P8" ]] || { echo "✗ $P8 is missing (Apple won't re-download it)."; exit 1; }
TOKEN="$(grep '^SUPABASE_ACCESS_TOKEN=' "$REPO/.env" | cut -d= -f2-)"
REF="$(grep '^SUPABASE_PROJECT_REF=' "$REPO/.env" | cut -d= -f2-)"
[[ -n "$TOKEN" && -n "$REF" ]] || { echo "✗ SUPABASE_ACCESS_TOKEN / SUPABASE_PROJECT_REF not in .env"; exit 1; }

mkdir -p "$DEST"
cp "$REPO/scripts/apple-secret-renew.mjs" "$DEST/apple-secret-renew.mjs"
cp "$P8" "$DEST/AuthKey.p8"
cat > "$DEST/.env.apple-renew" <<ENV
SUPABASE_ACCESS_TOKEN=$TOKEN
SUPABASE_PROJECT_REF=$REF
APPLE_P8_PATH=$DEST/AuthKey.p8
APPLE_KEY_ID=$KEY_ID
APPLE_TEAM_ID=AR3LCY2JB4
APPLE_SERVICES_ID=com.arielbiton.rinkhockeyil.web
ENV
chmod 600 "$DEST/AuthKey.p8" "$DEST/.env.apple-renew"

cat > "$DEST/run.sh" <<RUNNER
#!/bin/zsh
# Generated by install-apple-secret-agent.sh — edit the repo copy, not this.
set -u
LOG="\$HOME/Library/Logs/apple-secret.log"
mkdir -p "\$(dirname "\$LOG")"
{
  echo "──────── \$(date '+%Y-%m-%d %H:%M:%S %Z') ────────"
  cd "$DEST" || exit 1
  set -a; source ./.env.apple-renew; set +a
  "$NODE" apple-secret-renew.mjs "\$@"
  rc=\$?
  echo "exit=\$rc"
  # A silent failure here only shows up months later as a dead Apple button.
  [[ \$rc -eq 0 ]] || osascript -e 'display notification "Apple sign-in secret renewal FAILED — see ~/Library/Logs/apple-secret.log" with title "rinkhockeyIL"'
} >> "\$LOG" 2>&1
RUNNER
chmod +x "$DEST/run.sh"

mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/install-apple-secret-agent.sh. Runs the copy in ~/.rinkhockey,
     not the repo: see that script for why (macOS TCC on ~/Documents). -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>/bin/zsh</string><string>$DEST/run.sh</string></array>
  <key>StartCalendarInterval</key>
  <dict><key>Day</key><integer>1</integer><key>Hour</key><integer>10</integer><key>Minute</key><integer>0</integer></dict>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/apple-secret.launchd.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/apple-secret.launchd.log</string>
</dict>
</plist>
PLISTEOF

plutil -lint "$PLIST" >/dev/null
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"

echo "✓ installed to $DEST"
echo "  runs the 1st of every month, 10:00"
echo "  log:  ~/Library/Logs/apple-secret.log"
echo "  test: $DEST/run.sh --dry-run"
echo "  now:  launchctl kickstart -p gui/\$(id -u)/$LABEL"
echo "  off:  launchctl bootout gui/\$(id -u)/$LABEL"
